name: Deploy Sphinx Site
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v2

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Install required dependencies
        run: pip install -r requirements.txt

      - name: Build the site with sphinx
        run: |
          sphinx-build -b dirhtml . _build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload built sphinx site
          path: '_build/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
